import image1 from '../assets/Image1.png'
import image2 from '../assets/Image2.png'
import image3 from '../assets/Image3.png'
import image4 from '../assets/Image4.png'
export const Data =[
    {
        title:'BKM Yaz Etkinlikleri Zengin Mutfağı',
        image:image1,
        explanation:`1978 yılında ilk kez İstanbul Şehir Tiyatrolarında bu oyunda aşçı Lütfü Usta'yı canlandıran Şener Şen, 40 yıl aradan sonra aynı rolde ve genç bir jenerasyonu da tiyatro severlerle buluşturmak üzere yeniden sahnelenecek. `,
        explanationResp:`1978 yılında ilk kez İstanbul Şehir Tiyatrolarında bu oyunda aşçı Lütfü Usta'yı canlandıran Şener Şen, 40 yıl aradan sonra aynı rolde ve genç bir jenerasyonu da tiyatro severlerle buluşturmak üzere yeniden sahnelenecek. `,
        location:'Maximum UNIQ Hall',
        date:'7',
        dateDay:'Salı',
        dateMonth:'Eylül',
        dateTime:'21:15',
        content:'TİYATRO',
        color:'#FF0D87',
        bgColor:'#B77CB8',
    },
    {
        title:'Yasemin Sakallıoğlu',
        image:image2,
        explanation:`1978 yılında ilk kez İstanbul Şehir Tiyatrolarında bu oyunda aşçı Lütfü Usta'yı canlandıran Şener Şen, 40 yıl aradan sonra aynı rolde ve genç bir jenerasyonu da tiyatro severlerle buluşturmak üzere yeniden sahnelenecek. `,
        explanationResp:`1978 yılında ilk kez İstanbul Şehir Tiyatrolarında bu oyunda aşçı Lütfü Usta'yı canlandıran Şener Şen, 40 yıl aradan sonra aynı rolde ve genç bir jenerasyonu da tiyatro severlerle buluşturmak üzere yeniden sahnelenecek. `,
        location:'Maximum UNIQ Hall',
        date:'8',
        dateDay:'Çarşamba',
        dateMonth:'Eylül',
        dateTime:'21:15',
        content:'STAND UP',
        color:'#FF0D87',
        bgColor:'#F19653',
    },
    {
        title:`Sinema Keyfi: Rifkin's Festival`,
        image:image3,
        explanation:`1978 yılında ilk kez İstanbul Şehir Tiyatrolarında bu oyunda aşçı Lütfü Usta'yı canlandıran Şener Şen, 40 yıl aradan sonra aynı rolde ve genç bir jenerasyonu da tiyatro severlerle buluşturmak üzere yeniden sahnelenecek. `,
        explanationResp:`1978 yılında ilk kez İstanbul Şehir Tiyatrolarında bu oyunda aşçı Lütfü Usta'yı canlandıran Şener Şen, 40 yıl aradan sonra aynı rolde ve genç bir jenerasyonu da tiyatro severlerle buluşturmak üzere yeniden sahnelenecek. `,
        location:'Maximum UNIQ Hall',
        date:'7',
        dateDay:'Salı',
        dateMonth:'Eylül',
        dateTime:'21:15',
        content:'SİNEMA',
        color:'#FF0D87',
        bgColor:'#F07266',
    },
    {
        title:'BKM Yaz Etkinlikleri Zengin Mutfağı',
        image:image1,
        explanation:`1978 yılında ilk kez İstanbul Şehir Tiyatrolarında bu oyunda aşçı Lütfü Usta'yı canlandıran Şener Şen, 40 yıl aradan sonra aynı rolde ve genç bir jenerasyonu da tiyatro severlerle buluşturmak üzere yeniden sahnelenecek. `,
        explanationResp:`1978 yılında ilk kez İstanbul Şehir Tiyatrolarında bu oyunda aşçı Lütfü Usta'yı canlandıran Şener Şen, 40 yıl aradan sonra aynı rolde ve genç bir jenerasyonu da tiyatro severlerle buluşturmak üzere yeniden sahnelenecek. `,
        location:'Maximum UNIQ Hall',
        date:'7',
        dateDay:'Salı',
        dateMonth:'Eylül',
        dateTime:'21:15',
        content:'KONSER',
        color:'#FF0D87',
        bgColor:'#9FAE5D',
    },
    {
        title:'Yasemin Sakallıoğlu',
        image:image2,
        explanation:`1978 yılında ilk kez İstanbul Şehir Tiyatrolarında bu oyunda aşçı Lütfü Usta'yı canlandıran Şener Şen, 40 yıl aradan sonra aynı rolde ve genç bir jenerasyonu da tiyatro severlerle buluşturmak üzere yeniden sahnelenecek. `,
        explanationResp:`1978 yılında ilk kez İstanbul Şehir Tiyatrolarında bu oyunda aşçı Lütfü Usta'yı canlandıran Şener Şen, 40 yıl aradan sonra aynı rolde ve genç bir jenerasyonu da tiyatro severlerle buluşturmak üzere yeniden sahnelenecek. `,
        location:'Maximum UNIQ Hall',
        date:'7',
        dateDay:'Salı',
        dateMonth:'Eylül',
        dateTime:'21:15',
        content:'STAND UP',
        color:'#FF0D87',
        bgColor:'#F19653',
    },
    {
        title:`Sinema Keyfi: Rifkin's Festival`,
        image:image4,
        explanation:`1978 yılında ilk kez İstanbul Şehir Tiyatrolarında bu oyunda aşçı Lütfü Usta'yı canlandıran Şener Şen, 40 yıl aradan sonra aynı rolde ve genç bir jenerasyonu da tiyatro severlerle buluşturmak üzere yeniden sahnelenecek. `,
        explanationResp:`1978 yılında ilk kez İstanbul Şehir Tiyatrolarında bu oyunda aşçı Lütfü Usta'yı canlandıran Şener Şen, 40 yıl aradan sonra aynı rolde ve genç bir jenerasyonu da tiyatro severlerle buluşturmak üzere yeniden sahnelenecek. `,
        location:'Maximum UNIQ Hall',
        date:'7',
        dateDay:'Salı',
        dateMonth:'Eylül',
        dateTime:'21:15',
        content:'SİNEMA',
        color:'#FF0D87',
        bgColor:'#F07266',
    },
]